#!/bin/bash

# Useful commands for development

echo "===========================================\"
echo "DALN WebBanHang - Development Commands"
echo "===========================================\"
echo ""

echo "THONG TIN HE THONG:"
echo "  PHP Version:       $(php -v | head -1)"
echo "  Composer Version:  $(composer -V | head -1)"
echo "  Node Version:      $(node -v)"
echo "  NPM Version:       $(npm -v)"
echo ""

echo "KHOI DONG:"
echo "  1. Start Dev Server:"
echo "     bash /workspaces/DALN_WebBanHang/start-dev.sh"
echo ""
echo "  2. Backend Only:"
echo "     cd /workspaces/DALN_WebBanHang/techshop"
echo "     php artisan serve --host=0.0.0.0 --port=8000"
echo ""
echo "  3. Frontend Only:"
echo "     cd /workspaces/DALN_WebBanHang/techshop"
echo "     npm run dev"
echo ""
echo "  4. Build Frontend:"
echo "     cd /workspaces/DALN_WebBanHang/techshop"
echo "     npm run build"
echo ""

echo "DATABASE:"
echo "  1. Run Migrations:"
echo "     cd /workspaces/DALN_WebBanHang/techshop"
echo "     php artisan migrate"
echo ""
echo "  2. Seed Database:"
echo "     php artisan db:seed"
echo ""
echo "  3. Fresh Database:"
echo "     php artisan migrate:fresh --seed"
echo ""

echo "DEPENDENCIES:"
echo "  1. Update Composer:"
echo "     sudo composer self-update"
echo "     composer update"
echo ""
echo "  2. Update NPM:"
echo "     npm install"
echo "     npm update"
echo ""

echo "DEBUGGING:"
echo "  1. Artisan Tinker:"
echo "     php artisan tinker"
echo ""
echo "  2. Check Routes:"
echo "     php artisan route:list"
echo ""
echo "  3. View Logs:"
echo "     tail -f storage/logs/laravel.log"
echo ""

echo "TESTING:"
echo "  1. Run Tests:"
echo "     php artisan test"
echo ""
echo "  2. Run Specific Test:"
echo "     php artisan test tests/Unit/YourTest.php"
echo ""

echo "GIT OPERATIONS:"
echo "  1. Check Status:"
echo "     git status"
echo ""
echo "  2. View Changes:"
echo "     git diff"
echo ""
echo "  3. Commit & Push:"
echo "     git add ."
echo "     git commit -m 'Your message'"
echo "     git push origin main"
echo ""

echo "PROTECTED FILES (Never commit):"
echo "  .env"
echo "  .vscode/"
echo "  setup-*.sh"
echo "  ca.pem"
echo "  node_modules/"
echo "  vendor/"
echo ""

echo "DOCUMENTATION:"
echo "  - GIT_WORKFLOW_GUIDE.md"
echo "  - CODESPACE_SETUP_COMPLETE.md"
echo "  - QUICK_START.md"
echo ""

echo "TIP: De chay 2 dev server cung luc:"
echo "  Mo 2 terminal:"
echo "  Terminal 1: cd techshop && php artisan serve --host=0.0.0.0 --port=8000"
echo "  Terminal 2: cd techshop && npm run dev"
echo ""
